### ISSUE TITLE
Decide between using `eq` and `eql` matcher in specs and keep it consistent

### ISSUE THREAD

**Issue by Azdaroth** [BookingSync/bookingsync-api#106]

**Comment by JulienItard** [comment]
I vote for `eql`. It's more strict than `eq` and prevent more errors.

**Comment by thilonel** [comment]
I have "never" used `eql`.

**Comment by Azdaroth** [comment]
I'd go with `eq` if not necessary, the same reason why we use `==` in code and not `eql`, `eq` matches is doing comparison with `==` and `eql` with `eql`.
