### ISSUE TITLE
NoMethodError on accessing unauthorized attribute

### ISSUE THREAD

**Issue by kaizencodes** [BookingSync/bookingsync-api#112]
accessing an attribute that we have no scopes for results
```
NoMethodError: undefined method `attribute' for #<BookingSync::API::Resource>
```

a better response would be `access to "attribute" is not granted`

low priority. fix when time allows

**Comment by thilonel** [comment]
@kaizencodes this is an API v3 issue, and we don't want to spend more time on that than we must. Going towards v4.
Also, don't open issues like this, submit a PR right on spot if you feel like or just leave it. We'll never pick stuff like this up, it's just clutter.
