### ISSUE TITLE
Support upcoming inbox endpoints

### ISSUE THREAD

**Issue by JovicaSusa** [BookingSync/bookingsync-api#116]
We need to add support for upcoming Inbox endpoints:
- Attachments
- Conversations
- Messages
- Participants

**Comment by thilonel** [comment]
@JovicaSusa this needs an estimate and an app label.

**Comment by JovicaSusa** [comment]
@thilonel I wanted to add them but no labels for that are available for this app, so thought that's not necessary here :)

**Comment by thilonel** [comment]
@JovicaSusa nope, I just haven't added them yet. Please create a label `BookingSync-API` for the repo, and also the complexity labels, as per the docs: https://knowledgedatabase.happystay.com/en/tech-team-ticket-management
